export const catalogCategories = ['Sofás', 'Camas', 'Mesas de comedor', 'Sillas', 'Mesas de centro', 'Oficina', 'Decoración'] as const;
export type Category = typeof catalogCategories[number] | string;
export type ProductStatus = 'draft' | 'published';
export type InventoryStatus = 'in_stock' | 'low_stock' | 'made_to_order' | 'out_of_stock';
export type ProductColorVariant = {
  id: string;
  name: string;
  hex: string;
  imageUrl?: string;
  imageStoragePath?: string | null;
  sortOrder: number;
};
export type Product = {
  id: string;
  slug: string;
  name: string;
  category: Category;
  price: number;
  description: string;
  images: string[];
  materials: string[];
  dimensions: string;
  colors: string[];
  variants?: ProductColorVariant[];
  featured: boolean;
  tags: string[];
  status?: ProductStatus;
  inventoryStatus?: InventoryStatus;
  leadTimeDays?: number | null;
  sortOrder?: number;
};
