import { ArrowRight, MapPin } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { business, whatsappLink } from '../config/business';
import { products } from '../data/products';
import { ProductCard } from '../components/ProductCard';

const image=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1500&q=85`;
type Kind='spaces'|'collections'|'inspiration'|'about';
const rooms=[
 ['Sala','El lugar donde la casa se abre. Sofas profundos, mesas bajas y texturas que invitan a alargar la conversacion.','photo-1616486338812-3dadae4b4ace','sala','Para una sala equilibrada, empieza por el sofa y deja al menos 70 cm de paso alrededor de la mesa de centro.'],
 ['Dormitorio','Menos estimulos, mejores mananas. Cabeceros suaves, maderas claras y una paleta que acompana el descanso.','photo-1615529162924-f8605388461d','dormitorio','Elige la cama antes que el resto. Deja 60 cm libres a cada lado para circular y ubicar una mesa de noche.'],
 ['Comedor','Una mesa no mide solo centimetros: mide encuentros. Elige tamano, material y sillas para tu forma de recibir.','photo-1617806118233-18e1de247200','comedor','Para seis personas, considera una mesa de 180 a 220 cm y reserva 90 cm detras de cada silla para moverla con comodidad.'],
 ['Estudio','Disenamos apoyo para las ideas: superficies tranquilas, almacenaje discreto y una silla que acompana.','photo-1594620302200-9a762244a156','oficina','Prioriza una superficie de 120 cm o mas, luz lateral y almacenaje cercano para mantener la mesa despejada.']
] as const;
const editorial={
 collections:{label:'COLECCIONES CASA NATIVA',title:<>Un lenguaje para<br/>cada forma de <em>vivir.</em></>,intro:'Las colecciones son puntos de vista, no conjuntos cerrados. Combinalas libremente para construir una casa con voz propia.',items:[['NATURAL','Materia que se siente','Roble, lino y piedra en tonos calidos para espacios luminosos.','photo-1616486338812-3dadae4b4ace','Explorar Natural'],['URBANA','Contraste con intencion','Madera oscura, metal mate y perfiles definidos para ritmos contemporaneos.','photo-1497366754035-f200968a6e72','Explorar Urbana'],['NORDICA','Claridad cotidiana','Formas ligeras y funcionalidad serena. Todo lo necesario, nada que distraiga.','photo-1615529162924-f8605388461d','Explorar Nordica']]},
 inspiration:{label:'CUADERNO DE CASA',title:<>Ideas que ayudan<br/>a mirar tu casa <em>distinto.</em></>,intro:'Guias breves para tomar decisiones con calma: distribucion, escala, materiales y las preguntas que hacer antes de comprar.',items:[['LECTURA 01','Como hacer que una sala pequena se sienta generosa','La clave esta en definir circulacion, altura visual y una pieza principal que haga el trabajo.','photo-1616486338812-3dadae4b4ace','Leer la guia'],['LECTURA 02','Elegir una mesa para las reuniones que si tienes','Cuatro medidas, dos materiales y una pregunta: cuantas personas se sientan a comer cada semana?','photo-1617806118233-18e1de247200','Leer la guia'],['LECTURA 03','Maderas claras y calidez','Mezcla vetas, textiles y piedra para que una base neutra tenga profundidad.','photo-1618220179428-22790b461013','Leer la guia']]}
};
const collections:{name:string;slug:string;statement:string;description:string;photo:string;ideal:string;materials:string[];palette:string[];productIds:string[]}[]=[
 {name:'Natural',slug:'coleccion-natural',statement:'Materia que se siente.',description:'Roble, lino y piedra en tonos cálidos para una casa luminosa, serena y conectada con lo esencial.',photo:'photo-1616486338812-3dadae4b4ace',ideal:'Ideal para espacios con luz natural y personas que prefieren materiales honestos.',materials:['Roble','Lino','Travertino'],palette:['#d7c5a9','#b6a18a','#e6dfd0'],productIds:['p1','p2','p5']},
 {name:'Urbana',slug:'coleccion-urbana',statement:'Contraste con intención.',description:'Madera oscura, metal mate y perfiles definidos para departamentos y ritmos contemporáneos.',photo:'photo-1497366754035-f200968a6e72',ideal:'Ideal para ambientes compactos que buscan un gesto gráfico y funcional.',materials:['Roble oscuro','Acero mate','Textil carbón'],palette:['#252724','#665d54','#a59c8d'],productIds:['p6']},
 {name:'Nórdica',slug:'coleccion-nordica',statement:'Claridad cotidiana.',description:'Formas ligeras, tonos de avena y funcionalidad serena. Todo lo necesario, nada que distraiga.',photo:'photo-1615529162924-f8605388461d',ideal:'Ideal para quienes buscan descanso visual, piezas ligeras y orden cotidiano.',materials:['Fresno','Bouclé','Pino'],palette:['#eee8dc','#d7cdbd','#b9ae9a'],productIds:['p3','p4']}
] as const;
function Spaces(){return <><section className="page-hero"><p className="eyebrow">GUIA POR AMBIENTE</p><h1>Cada habitacion tiene<br/>su propio <em>ritmo.</em></h1><p>No partimos de un mueble aislado. Partimos de lo que haces alli: descansar, compartir, concentrarte o dejar pasar la tarde.</p></section><section className="space-guide">{rooms.map(([title,description,photo,space,tip])=><article className="room-guide" key={title}><div className="room-intro"><img src={image(photo)} alt={`${title} Casa Nativa`}/><div><p className="eyebrow">{title.toUpperCase()}</p><h2>{title}</h2><p>{description}</p><aside><b>Antes de elegir</b><p>{tip}</p></aside><div className="room-actions"><Link className="dark-button" to={`/catalog?space=${space}`}>Ver todo para {title.toLowerCase()} <ArrowRight/></Link><a href={whatsappLink(`Hola, necesito ayuda para amoblar mi ${title.toLowerCase()}.`)} target="_blank" rel="noreferrer">Pedir asesoria <ArrowRight/></a></div></div></div></article>)}</section></>}
function Collections(){return <><section className="page-hero"><p className="eyebrow">COLECCIONES CASA NATIVA</p><h1>Un lenguaje para<br/>cada forma de <em>vivir.</em></h1><p>Elige una dirección visual para tu casa. Luego adapta las piezas, el tamaño y los materiales a tu vida real.</p></section><section className="collection-guide">{collections.map(collection=>{const curated=products.filter(p=>collection.productIds.includes(p.id));return <article className="collection-guide-item" key={collection.name}><div className="collection-intro"><img src={image(collection.photo)} alt={`Colección ${collection.name}`}/><div><p className="eyebrow">COLECCIÓN {collection.name.toUpperCase()}</p><h2>{collection.statement}</h2><p>{collection.description}</p><p className="collection-ideal"><b>Para quién es</b>{collection.ideal}</p><div className="collection-spec"><div><b>Materiales</b><span>{collection.materials.join(' · ')}</span></div><div><b>Paleta</b><span className="palette">{collection.palette.map(color=><i key={color} style={{background:color}}/>)}</span></div></div><div className="room-actions"><Link className="dark-button" to={`/catalog?collection=${collection.slug}`}>Comprar {collection.name} <ArrowRight/></Link><a href={whatsappLink(`Hola, necesito ayuda para crear un espacio con la colección ${collection.name}.`)} target="_blank" rel="noreferrer">Pedir asesoría <ArrowRight/></a></div></div></div><div className="curated collection-curated"><div><p className="eyebrow">PIEZAS DE LA COLECCIÓN</p><span>{curated.length} piezas disponibles</span></div><div className="room-products">{curated.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></article>})}</section></>}
function Inspiration(){const page=editorial.inspiration;return <><section className="page-hero"><p className="eyebrow">{page.label}</p><h1>{page.title}</h1><p>{page.intro}</p></section><section className="story-list inspiration">{page.items.map(([number,title,description,photo,action])=><article key={title}><img src={image(photo)} alt={title}/><div><p className="eyebrow">{number}</p><h2>{title}</h2><p>{description}</p><Link to="/catalog">{action} <ArrowRight/></Link></div></article>)}</section></>}
function About(){return <><section className="page-hero about-hero"><p className="eyebrow">NUESTRA FORMA DE HACER</p><h1>Menos cosas.<br/>Mejores <em>historias.</em></h1><p>Casa Nativa nace en Quito para ayudar a construir hogares que envejecen con gracia, no modas que terminan rapido.</p></section><section className="about-story"><div><p className="eyebrow">NUESTRA PROMESA</p><h2>Elegimos piezas que te siguen el paso.</h2></div><p>Creemos que el buen diseno se reconoce con el tiempo: en una superficie que conserva su tacto, un sofa comodo y una mesa que reune recuerdos.</p></section><section className="principles"><img src={image('photo-1600210492486-724fe5c67fb0')} alt="Detalle de mobiliario de madera"/><div>{[['Materiales honestos','Maderas, textiles y acabados elegidos por su caracter y duracion.'],['Escala humana','Piezas pensadas para cuerpos, movimientos y hogares reales.'],['Acompanamiento cercano','Te ayudamos a decidir antes, durante y despues de elegir.']].map(([title,description],n)=><article key={title}><span>0{n+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="showroom-cta"><p className="eyebrow">MEJOR EN PERSONA</p><h2>Ven a sentarte,<br/><em>tocar y elegir.</em></h2><Link className="light-button" to="/contact">Conocer el showroom <ArrowRight/></Link></section></>}
export function Editorial({kind}:{kind:Kind}){if(kind==='spaces')return <Spaces/>;if(kind==='collections')return <Collections/>;if(kind==='about')return <About/>;return <Inspiration/>}
export function Contact(){return <section className="contact"><p className="eyebrow">HABLEMOS DE TU ESPACIO</p><h1>Ven a sentir<br/><em>los materiales.</em></h1><div className="contact-grid"><div><h2>Showroom</h2><p><MapPin/> {business.address}</p><p>{business.hours}</p><a className="dark-button" href={whatsappLink('Hola, quisiera agendar una visita al showroom.')}>Agendar visita</a></div><ContactForm/></div></section>}
function ContactForm(){const [sent,setSent]=useState(false);const [error,setError]=useState('');function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);if(!d.get('name')||!d.get('email')||!d.get('message'))return setError('Completa nombre, correo y mensaje.');setError('');setSent(true)}return <form className="contact-form" onSubmit={submit}>{sent?<div className="success"><h2>Mensaje recibido.</h2><p>Te responderemos muy pronto.</p></div>:<><label>Nombre<input name="name" required/></label><label>Correo electronico<input name="email" type="email" required/></label><label>Telefono<input name="phone" type="tel"/></label><label>En que te ayudamos?<textarea name="message" required/></label>{error&&<p className="error">{error}</p>}<button className="dark-button">Enviar mensaje</button></>}</form>}
