import { ArrowLeft, ArrowRight, Clock3 } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getInspirationGuide, inspirationGuides } from '../data/inspiration';
import { products } from '../data/products';
import { ProductCard } from '../components/ProductCard';
import { whatsappLink } from '../config/business';
import { NotFound } from './NotFound';

export function InspirationArticle(){const {slug}=useParams();const guide=getInspirationGuide(slug);if(!guide)return <NotFound/>;const selected=products.filter(product=>guide.productIds.includes(product.id));const next=inspirationGuides.find(item=>item.slug!==guide.slug);return <article className="article-page"><Link className="back" to="/inspiration"><ArrowLeft/> Volver a Inspiration</Link><header className="article-head"><div><p className="eyebrow">{guide.eyebrow}</p><h1>{guide.title}</h1><p>{guide.deck}</p><span><Clock3/>{guide.readTime}</span></div><img src={guide.coverImage} alt={guide.title}/></header><div className="article-layout"><aside className="article-index"><p className="eyebrow">EN ESTA GUÍA</p>{guide.sections.map((section,index)=><a href={`#paso-${index+1}`} key={section.title}>{String(index+1).padStart(2,'0')} {section.title}</a>)}</aside><div className="article-body"><p className="article-intro">{guide.intro}</p>{guide.sections.map((section,index)=><section id={`paso-${index+1}`} key={section.title}><span>{String(index+1).padStart(2,'0')}</span><h2>{section.title}</h2><p>{section.body}</p>{section.note&&<aside><b>Para recordar</b><p>{section.note}</p></aside>}</section>)}</div></div><section className="article-products"><div className="section-head"><div><p className="eyebrow">PIEZAS PARA ESTA GUÍA</p><h2>Empieza por<br/><em>lo esencial.</em></h2></div><Link className="dark-button" to={`/catalog?${guide.catalogFilter.startsWith('coleccion-')?'collection':'space'}=${guide.catalogFilter}`}>Ver selección <ArrowRight/></Link></div><div className="product-grid">{selected.map(product=><ProductCard key={product.id} product={product}/>)}</div></section><section className="article-cta"><p className="eyebrow">LLEVEMOS LA IDEA A TU ESPACIO</p><h2>¿Quieres una segunda<br/><em>mirada?</em></h2><a className="light-button" href={whatsappLink(guide.whatsappMessage)} target="_blank" rel="noreferrer">Hablar con un asesor <ArrowRight/></a></section>{next&&<Link className="next-guide" to={`/inspiration/${next.slug}`}><p className="eyebrow">SIGUIENTE LECTURA</p><h2>{next.title}</h2><ArrowRight/></Link>}</article>}
